version: '3.3'
services:
    app:
        container_name: beershop
        image: beershop
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:8090"
        depends_on:
            - mysql
        restart: on-failure
    mysql:
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        image: mysql:latest
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: beershop_db
            MYSQL_USER: app_user
            MYSQL_PASSWORD: password

docker exec -it "ID" sh --- в командную строку в контейнере
mvn install -DskipTests