version: '3.2'
services:
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: beershop
            MYSQL_USER: app_user
            MYSQL_PASSWORD: password
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8090"
        depends_on:
            - db
